#!/bin/bash
set -e

if [ "$1" = "purge" ]
then
  [ -f "/etc/ferm6.d/20iserv-ipv6.conf" ] && rm -f /etc/ferm6.d/20iserv-ipv6.conf
  [ -f "/etc/ferm6.d/99defaults.conf" ] && rm -f /etc/ferm6.d/99defaults.conf
  [ -d "/etc/ferm6.d" ] && (rmdir /etc/ferm6.d || true)
  [ -f "/etc/ferm/ferm6.conf" ] && rm -f /etc/ferm/ferm6.conf 
fi

#DEBHELPER#
